[env:feather_rp2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = adafruit_feather
framework = arduino
board_build.core = earlephilhower
lib_deps = adafruit/Adafruit TinyUSB Library@^3.1.0

build_flags =
  -D USE_TINYUSB
  -D CFG_TUD_CDC=1
  -D USB_VID=0x239A
  -D USB_PID=0x80F1
  -D USB_MANUFACTURER="Adafruit"
  -D USB_PRODUCT="Feather RP2040 TTL"
  -D USB_SERIAL="HYPERSTUDY-TTL-001"